-- CreateTable
CREATE TABLE `CPL_PL` (
    `KodeCPL` VARCHAR(50) NOT NULL,
    `KodePL` VARCHAR(50) NOT NULL,

    PRIMARY KEY (`KodeCPL`, `KodePL`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `CPL_PL` ADD CONSTRAINT `CPL_PL_KodeCPL_fkey` FOREIGN KEY (`KodeCPL`) REFERENCES `CPL_Prodi`(`KodeCPL`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CPL_PL` ADD CONSTRAINT `CPL_PL_KodePL_fkey` FOREIGN KEY (`KodePL`) REFERENCES `ProfilLulusan`(`KodePL`) ON DELETE RESTRICT ON UPDATE CASCADE;
