-- CreateTable
CREATE TABLE `ML_CPMK_SUBMK` (
    `IDMK` VARCHAR(50) NOT NULL,
    `KodeCPMK` VARCHAR(50) NOT NULL,
    `SubCPMK` VARCHAR(50) NOT NULL,

    PRIMARY KEY (`IDMK`, `KodeCPMK`, `SubCPMK`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ML_CPMK_SUBMK` ADD CONSTRAINT `ML_CPMK_SUBMK_IDMK_fkey` FOREIGN KEY (`IDMK`) REFERENCES `Mata_Kuliah`(`IDMK`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ML_CPMK_SUBMK` ADD CONSTRAINT `ML_CPMK_SUBMK_KodeCPMK_fkey` FOREIGN KEY (`KodeCPMK`) REFERENCES `CPMK`(`KodeCPMK`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `ML_CPMK_SUBMK` ADD CONSTRAINT `ML_CPMK_SUBMK_SubCPMK_fkey` FOREIGN KEY (`SubCPMK`) REFERENCES `SUB_CPMK`(`SubCPMK`) ON DELETE RESTRICT ON UPDATE CASCADE;
