-- CreateTable
CREATE TABLE `BK_MK` (
    `KodeBK` VARCHAR(50) NOT NULL,
    `IDMK` VARCHAR(50) NOT NULL,

    PRIMARY KEY (`KodeBK`, `IDMK`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `BK_MK` ADD CONSTRAINT `BK_MK_KodeBK_fkey` FOREIGN KEY (`KodeBK`) REFERENCES `Bahan_Kajian`(`KodeBK`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BK_MK` ADD CONSTRAINT `BK_MK_IDMK_fkey` FOREIGN KEY (`IDMK`) REFERENCES `Mata_Kuliah`(`IDMK`) ON DELETE RESTRICT ON UPDATE CASCADE;
