-- CreateTable
CREATE TABLE `CPL_BK_MK` (
    `KodeCPL` VARCHAR(50) NOT NULL,
    `KodeBK` VARCHAR(50) NOT NULL,
    `IDMK` VARCHAR(50) NOT NULL,

    PRIMARY KEY (`KodeCPL`, `KodeBK`, `IDMK`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `CPL_BK_MK` ADD CONSTRAINT `CPL_BK_MK_KodeCPL_fkey` FOREIGN KEY (`KodeCPL`) REFERENCES `CPL_Prodi`(`KodeCPL`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CPL_BK_MK` ADD CONSTRAINT `CPL_BK_MK_KodeBK_fkey` FOREIGN KEY (`KodeBK`) REFERENCES `Bahan_Kajian`(`KodeBK`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CPL_BK_MK` ADD CONSTRAINT `CPL_BK_MK_IDMK_fkey` FOREIGN KEY (`IDMK`) REFERENCES `Mata_Kuliah`(`IDMK`) ON DELETE RESTRICT ON UPDATE CASCADE;
