-- CreateTable
CREATE TABLE `SUB_CPMK` (
    `SubCPMK` VARCHAR(50) NOT NULL,
    `Uraian_SubCPMK` VARCHAR(255) NULL,

    PRIMARY KEY (`SubCPMK`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CPMK` (
    `KodeCPMK` VARCHAR(50) NOT NULL,
    `CPMK` VARCHAR(255) NULL,
    `SubCPMK` VARCHAR(50) NOT NULL,

    PRIMARY KEY (`KodeCPMK`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `CPMK` ADD CONSTRAINT `CPMK_SubCPMK_fkey` FOREIGN KEY (`SubCPMK`) REFERENCES `SUB_CPMK`(`SubCPMK`) ON DELETE RESTRICT ON UPDATE CASCADE;
